name: CI Advanced - Java + Maven + Docker + Trivy

on:
  push:
    branches: ["main", "master"]
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["main", "master"]

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:

  build-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

  build-docker-and-push:
    runs-on: ubuntu-latest
    needs: build-setup

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ewallet_pix_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd="pg_isready -U test -d ewallet_pix_db"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ------------------------------
      # Extrair versÃ£o do pom.xml
      # ------------------------------
      - name: Read version from pom.xml
        id: version
        run: |
          VERSION=$(mvn -q -Dexec.executable=echo \
            -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

    
          # ------------------------------
          # Build Docker image
          # ------------------------------
          - name: Build Docker image
            run: |
              docker build \
                -t jsrobert10/ewallet-pix-service:${{ steps.version.outputs.version }} \
                -t jsrobert10/ewallet-pix-service:${{ steps.branch.outputs.name }} \
                -t jsrobert10/ewallet-pix-service:latest \
                .

      # ------------------------------
      # Push Docker image
      # ------------------------------
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push jsrobert10/ewallet-pix-service:${{ steps.version.outputs.version }}
          docker push jsrobert10/ewallet-pix-service:${{ steps.branch.outputs.name }}
          docker push jsrobert10/ewallet-pix-service:latest

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ secrets.DOCKERHUB_USERNAME }}/ewallet-pix-service:latest"
          format: sarif
          output: trivy-results.sarif
