name: CI - Java + Maven + Docker Push

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:

  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      # -----------------------
      # Checkout
      # -----------------------
      - name: Checkout
        uses: actions/checkout@v4

      # -----------------------
      # Setup Java + cache
      # -----------------------
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # -----------------------
      # Maven build
      # -----------------------
      - name: Build Maven
        run: mvn -B clean package -DskipTests=false

      # -----------------------
      # Autenticação no DockerHub
      # -----------------------
      - name: Login no DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -----------------------
      # Build da imagem Docker
      # -----------------------
      - name: Build Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/ewallet-pix-service"
          VERSION="${{ github.run_number }}"

          echo "Building image $IMAGE_NAME:$VERSION"

          docker build -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$VERSION

      # -----------------------
      # Push da imagem
      # -----------------------
      - name: Push Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/ewallet-pix-service"
          VERSION="${{ github.run_number }}"

          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION
